const stoicGratitudeEnthusiasmQuotes = [
    "You have power over your mind, not outside events. Realize this, and you will find strength. - Marcus Aurelius",
    "The key is to keep company only with people who uplift you, whose presence calls forth your best. - Epictetus",
    "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
    "Waste no more time arguing about what a good man should be. Be one. - Marcus Aurelius",
    "The more we value things outside our control, the less control we have. - Epictetus",
    "Gratitude is not only the greatest of virtues but the parent of all others. - Marcus Tullius Cicero",
    "Cultivate the habit of being grateful for every good thing that comes to you, and to give thanks continuously. - Ralph Waldo Emerson",
    "When you arise in the morning, think of what a precious privilege it is to be alive, to breathe, to think, to enjoy, to love. - Marcus Aurelius",
    "Gratitude turns what we have into enough. - Aesop",
    "The root of joy is gratefulness. - David Steindl-Rast",
    "If it is not right, do not do it; if it is not true, do not say it. - Marcus Aurelius",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "The world is full of magical things patiently waiting for our wits to grow sharper. - Bertrand Russell",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Begin each day by telling yourself: Today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness. - Marcus Aurelius",
    "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment. - Marcus Aurelius",
    "The grateful heart sits at a continuous feast. - Proverb",
    "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult. - Seneca",
    "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has. - Epictetus",
    "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for. - Epicurus",
    "Gratitude is the fairest blossom that springs from the soul. - Henry Ward Beecher",
    "Enthusiasm is the mother of effort, and without it, nothing great was ever achieved. - Ralph Waldo Emerson",
    "To be content means that you realize you contain what you seek. - Alan Cohen",
    "We must find time to stop and thank the people who make a difference in our lives. - John F. Kennedy", 
    "Adversity reveals genius, prosperity conceals it. - Horace",
    "When you have to cope with a lot of problems, you're either going to sink or you're going to swim. - Tom Cruise",
    "The best way to predict your future is to create it. - Peter Drucker",
    "You are the master of your own ship; you are the captain of your soul. - Ernest Henley",
    "Even if you're on the right track, you'll get run over if you just sit there. - Will Rogers",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "What you do today can improve all your tomorrows. - Ralph Marston",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Perfection is not attainable, but if we chase perfection we can catch excellence. - Vince Lombardi",
    "Every morning we are born again. What we do today matters most. - Buddha",
    "The harder I work, the luckier I get. - Samuel Goldwyn",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Henry David Thoreau",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails. - William Arthur Ward",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "Don't count the days; make the days count. - Muhammad Ali",
    "In the depths of winter, I finally learned that within me there lay an invincible summer. - Albert Camus",
    "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg"
  ];
  

  
  

export default stoicGratitudeEnthusiasmQuotes;